[platformio]

[env]
platform = atmelavr
framework = arduino
lib_extra_dirs =
	libdeps
lib_deps =
    ;SoftwareSerial
    https://github.com/smalcolmbrown/LiquidCrystal_I2C.git
	https://github.com/PaoloP74/extEEPROM.git
    https://github.com/sstaub/Ethernet3.git
    https://github.com/stevemarple/IniFile.git
    https://github.com/arduino-libraries/SD.git
    https://github.com/geekfactory/FIFO.git
    https://github.com/ricaun/ArduinoUniqueID.git
    https://github.com/arduino-libraries/ArduinoMqttClient.git
upload_protocol = custom
;upload_port = /dev/tty.usbserial-20
upload_port = /dev/tty.usbmodem201
upload_flags =
    -V
    -D
;	-C
;	/home/nicholas/.platformio/packages/tool-avrdude/avrdude.conf
	-c
	wiring
	-b
	115200
	-p
    $BOARD_MCU
    -P
    $UPLOAD_PORT
;upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
;upload_command = scp .pio/build/ATmega328P/firmware.hex 192.168.0.181:tmp/
;upload_command = [ -e ".pio/build/ATmega328P/firmware.bin" ] && scp .pio/build/ATmega328P/firmware.bin pi@192.168.0.138:/home/pi/tools/firmware_cache/419.bin
upload_command = [ -e ".pio/build/ATmega2560/firmware.bin" ] && scp .pio/build/ATmega2560/firmware.bin nicholas@comm:/tmp/ && ssh comm "sudo mount /dev/sdf1 /data/sdX1 && sudo cp /tmp/firmware.bin /data/sdX1/ &&  sudo umount /data/sdX1"

extra_scripts =
	post:make_bin.py
	pre:inc_build_number.py

[env:ATmega2560]
platform = atmelavr
board = ATmega2560
board_build.f_cpu = 16000000L
;board_upload.maximum_size = 28672
;board_upload.maximum_size = 32768
build_flags =
    -Wno-unused-but-set-variable
    -Wno-shift-overflow
   -DETHERNET
   -DSDC
   -DWEB_GUI
   ;-DDEBUG
   ;-DRESET
   -DTRANSLATE
   -DHAS_I2C_LCD